name: 'ci'

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  ci:
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        version: [ '1.19', '1.20', '1.21', '1.22' ]

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Set up Go'
        uses: 'actions/setup-go@v4'
        with:
          go-version: ${{ matrix.version }}

      - name: 'Test'
        run: 'go test -v ./...'